# Copyright (C) 2016 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/huawei/cherry/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/huawei/cherry/proprietary/etc/firmware/fused_nvm_c8817d.bin:system/etc/firmware/fused_nvm_c8817d.bin \
    vendor/huawei/cherry/proprietary/etc/firmware/nfc_test.bin:system/etc/firmware/nfc_test.bin \
    vendor/huawei/cherry/proprietary/etc/nfc/hardfault.cfg:system/etc/nfc/hardfault.cfg \
    vendor/huawei/cherry/proprietary/etc/permissions/com.android.nfc.helper.xml:system/etc/permissions/com.android.nfc.helper.xml \
    vendor/huawei/cherry/proprietary/etc/permissions/com.android.qualcomm.qti.nfc_extras.xml:system/etc/permissions/com.android.qualcomm.qti.nfc_extras.xml \
    vendor/huawei/cherry/proprietary/etc/permissions/com.vzw.nfc.xml:system/etc/permissions/com.vzw.nfc.xml \
    vendor/huawei/cherry/proprietary/framework/com.android.nfc.helper.jar:system/framework/com.android.nfc.helper.jar \
    vendor/huawei/cherry/proprietary/framework/com.android.qualcomm.qti.nfc_extras.jar:system/framework/com.android.qualcomm.qti.nfc_extras.jar \
    vendor/huawei/cherry/proprietary/framework/com.vzw.nfc.jar:system/framework/com.vzw.nfc.jar \
    vendor/huawei/cherry/proprietary/vendor/lib/hw/nfc_nci.qc199x.default.so:system/vendor/lib/hw/nfc_nci.qc199x.default.so \
    vendor/huawei/cherry/proprietary/vendor/lib/libqnfc_nci_jni.so:system/vendor/lib/libqnfc_nci_jni.so \
    vendor/huawei/cherry/proprietary/vendor/lib/libqnfc-nci.so:system/vendor/lib/libqnfc-nci.so

PRODUCT_PACKAGES += \
    QNfc
