# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/huawei/u8815/setup-makefiles.sh


PRODUCT_COPY_FILES += \
    vendor/huawei/u8815/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/huawei/u8815/proprietary/bin/rild:system/bin/rild \
    vendor/huawei/u8815/proprietary/lib/libauth.so:system/lib/libauth.so \
    vendor/huawei/u8815/proprietary/lib/libcm.so:system/lib/libcm.so \
    vendor/huawei/u8815/proprietary/lib/libdiag.so:system/lib/libdiag.so \
    vendor/huawei/u8815/proprietary/lib/libdsm.so:system/lib/libdsm.so \
    vendor/huawei/u8815/proprietary/lib/libdss.so:system/lib/libdss.so \
    vendor/huawei/u8815/proprietary/lib/libgsdi_exp.so:system/lib/libgsdi_exp.so \
    vendor/huawei/u8815/proprietary/lib/libgstk_exp.so:system/lib/libgstk_exp.so \
    vendor/huawei/u8815/proprietary/lib/libgstk_exp.so:system/lib/libhwdrm1.so \
    vendor/huawei/u8815/proprietary/lib/libgstk_exp.so:system/lib/libhwdrm1_jni.so \
    vendor/huawei/u8815/proprietary/lib/libgstk_exp.so:system/lib/libhwnv.so \
    vendor/huawei/u8815/proprietary/lib/libgstk_exp.so:system/lib/libhwrpc.so \
    vendor/huawei/u8815/proprietary/lib/libmmgsdilib.so:system/lib/libmmgsdilib.so \
    vendor/huawei/u8815/proprietary/lib/libnv.so:system/lib/libnv.so \
    vendor/huawei/u8815/proprietary/lib/liboncrpc.so:system/lib/liboncrpc.so \
    vendor/huawei/u8815/proprietary/lib/libpbmlib.so:system/lib/libpbmlib.so \
    vendor/huawei/u8815/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    vendor/huawei/u8815/proprietary/lib/libqueue.so:system/lib/libqueue.so \
    vendor/huawei/u8815/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/huawei/u8815/proprietary/lib/libril-qc-1.so:system/lib/libril-qc-1.so \
    vendor/huawei/u8815/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/huawei/u8815/proprietary/lib/libwms.so:system/lib/libwms.so \
    vendor/huawei/u8815/proprietary/lib/libwmsts.so:system/lib/libwmsts.so \
    vendor/huawei/u8815/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/huawei/u8815/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/huawei/u8815/proprietary/lib/libmmipl.so:system/lib/libmmipl.so
